/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paquete;

import java.awt.Color;
import static java.lang.Math.PI;
import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 *
 * @author luisg
 */
public class ObjetoSalpicadero extends javax.swing.JFrame {

    private static ClienteMotor motor;
    private double distanciaRecorrida = 0;
    private double distanciaReciente = 0;
    /**
     * Creates new form FramePrincipal
     */
    public ObjetoSalpicadero() {
        initComponents();
        this.VelocimetroCampo.setText("");
        Freno.setEnabled(false);
        Acelerador.setEnabled(false);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMandos = new javax.swing.JPanel();
        Informacion = new javax.swing.JLabel();
        EncendidoApagado = new javax.swing.JToggleButton();
        Acelerador = new javax.swing.JToggleButton();
        Freno = new javax.swing.JToggleButton();
        labelMandos = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelSalpicadero = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        VelocimetroLabel = new javax.swing.JLabel();
        VelocimetroCampo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CuentaKilometrosLabel = new javax.swing.JLabel();
        ContadorRecienteLabel = new javax.swing.JLabel();
        ContadorTotalLabel = new javax.swing.JLabel();
        ContadorRecienteCampo = new javax.swing.JLabel();
        ContadorTotalCampo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        CuentaRevolucionesLabel = new javax.swing.JLabel();
        RevolucionesCampo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMandos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Informacion.setForeground(new java.awt.Color(255, 0, 51));
        Informacion.setText("Informacion");

        EncendidoApagado.setForeground(new java.awt.Color(102, 255, 102));
        EncendidoApagado.setText("ENCENDER");
        EncendidoApagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncendidoApagadoActionPerformed(evt);
            }
        });

        Acelerador.setText("ACELERAR");
        Acelerador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceleradorActionPerformed(evt);
            }
        });

        Freno.setText("FRENAR");
        Freno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenoActionPerformed(evt);
            }
        });

        labelMandos.setText("Mandos");

        javax.swing.GroupLayout panelMandosLayout = new javax.swing.GroupLayout(panelMandos);
        panelMandos.setLayout(panelMandosLayout);
        panelMandosLayout.setHorizontalGroup(
            panelMandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMandosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(labelMandos)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelMandosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(EncendidoApagado, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 167, Short.MAX_VALUE)
                .addComponent(Acelerador, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(Freno, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(panelMandosLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(Informacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMandosLayout.setVerticalGroup(
            panelMandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMandosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMandos)
                .addGap(17, 17, 17)
                .addComponent(Informacion)
                .addGap(39, 39, 39)
                .addGroup(panelMandosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncendidoApagado)
                    .addComponent(Acelerador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Freno))
                .addGap(16, 16, 16))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelSalpicadero.setText("Salpicadero");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        VelocimetroLabel.setText("Velocímetro");

        VelocimetroCampo.setText("0");

        jLabel1.setText("km/h");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(VelocimetroLabel)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(VelocimetroCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VelocimetroLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VelocimetroCampo)
                    .addComponent(jLabel1))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CuentaKilometrosLabel.setText("CuentaKilometros");

        ContadorRecienteLabel.setText("Contador Reciente");

        ContadorTotalLabel.setText("ContadorTotal");

        ContadorRecienteCampo.setText("0");

        ContadorTotalCampo.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ContadorRecienteLabel)
                            .addComponent(ContadorTotalLabel))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ContadorRecienteCampo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(ContadorTotalCampo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(CuentaKilometrosLabel))
                .addContainerGap(425, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CuentaKilometrosLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContadorRecienteLabel)
                    .addComponent(ContadorRecienteCampo))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContadorTotalLabel)
                    .addComponent(ContadorTotalCampo))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CuentaRevolucionesLabel.setText("CuentaRevoluciones");

        RevolucionesCampo.setText("0");

        jLabel2.setText("RPM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CuentaRevolucionesLabel)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(RevolucionesCampo)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)))
                .addContainerGap(546, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(CuentaRevolucionesLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RevolucionesCampo)
                    .addComponent(jLabel2))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelSalpicadero)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelSalpicadero)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelMandos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(panelMandos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EncendidoApagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncendidoApagadoActionPerformed
        if(EncendidoApagado.isSelected()){
            Acelerador.setEnabled(true);
            Freno.setEnabled(true);
            EncendidoApagado.setText("APAGAR");
            EncendidoApagado.setForeground(Color.red);
            Informacion.setText("ENCENDIDO");
            motor.estado = EstadoMotor.ENCENDIDO;
        } else{
            if(Acelerador.isSelected()) Acelerador.doClick();
            Acelerador.setEnabled(false);
            if(Freno.isSelected())Freno.doClick();
            Freno.setEnabled(false);
            EncendidoApagado.setText("ENCENDER");
            EncendidoApagado.setForeground(Color.green);
            Informacion.setText("APAGADO");
            motor.estado = EstadoMotor.APAGADO;
        }
    }//GEN-LAST:event_EncendidoApagadoActionPerformed

    private void AceleradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceleradorActionPerformed
        // TODO add your handling code here:
        if(Acelerador.isSelected()){
            this.ejecutar(motor.getRPM(), EstadoMotor.ACELERANDO);
            Acelerador.setText("Soltar acelerador");
            Acelerador.setForeground(Color.red);
            if(Freno.isSelected())Freno.doClick();
            Informacion.setText("ACELERANDO");
            motor.estado = EstadoMotor.ACELERANDO;
        }else{
            Acelerador.setText("ACELERAR");
            Informacion.setText("ENCENDIDO");
            motor.estado = EstadoMotor.ENCENDIDO;
        }
    }//GEN-LAST:event_AceleradorActionPerformed

    private void FrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenoActionPerformed
        if( Freno.isSelected() ){
            Freno.setText("Soltar freno");
            if(Acelerador.isSelected())Acelerador.doClick();
            Informacion.setText("FRENANDO");
            motor.estado = EstadoMotor.FRENANDO;
        }else{
            Freno.setText("FRENAR");
            Informacion.setText("Encendido");
            motor.estado = EstadoMotor.ENCENDIDO;
            
        }
    }//GEN-LAST:event_FrenoActionPerformed

    public void ejecutar(double revoluciones, EstadoMotor estadoMotor){
      
        double velocidad = (2 * PI * 0.15f * revoluciones * (60f/1000f));
        
        BigDecimal bd = new BigDecimal(velocidad).setScale(2, RoundingMode.HALF_UP);
        double vel2 = bd.doubleValue();
        this.VelocimetroCampo.setText(vel2 + "");
        
        BigDecimal bd2 = new BigDecimal(revoluciones).setScale(2, RoundingMode.HALF_UP);
        double rev2 = bd2.doubleValue();
        this.RevolucionesCampo.setText(rev2 + "");
        
        double distancia = velocidad * 0.0015;
        if (motor.estado == EstadoMotor.APAGADO) 
            distanciaReciente = 0;
        else if (motor.estado == EstadoMotor.ACELERANDO || motor.estado == EstadoMotor.FRENANDO){
            distanciaReciente = distanciaReciente + distancia;
            distanciaRecorrida = distanciaRecorrida + distancia;
        }
        
        BigDecimal bd3 = new BigDecimal(distanciaReciente).setScale(2, RoundingMode.HALF_UP);
        double reciente = bd3.doubleValue();
        this.ContadorRecienteCampo.setText(reciente + "");
        
        BigDecimal bd4 = new BigDecimal(distanciaRecorrida).setScale(2, RoundingMode.HALF_UP);
        double recorrida = bd4.doubleValue();
        this.ContadorTotalCampo.setText(recorrida + "");

    }
    
    public static void aplicarMotor(ClienteMotor mot){
        motor = mot;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Acelerador;
    private javax.swing.JLabel ContadorRecienteCampo;
    private javax.swing.JLabel ContadorRecienteLabel;
    private javax.swing.JLabel ContadorTotalCampo;
    private javax.swing.JLabel ContadorTotalLabel;
    private javax.swing.JLabel CuentaKilometrosLabel;
    private javax.swing.JLabel CuentaRevolucionesLabel;
    private javax.swing.JToggleButton EncendidoApagado;
    private javax.swing.JToggleButton Freno;
    private javax.swing.JLabel Informacion;
    private javax.swing.JLabel RevolucionesCampo;
    private javax.swing.JLabel VelocimetroCampo;
    private javax.swing.JLabel VelocimetroLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelMandos;
    private javax.swing.JLabel labelSalpicadero;
    private javax.swing.JPanel panelMandos;
    // End of variables declaration//GEN-END:variables
}
