/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modeloObservable;

import java.util.Observable;
import java.util.Observer;
/**
 *
 * @author albertollamasgonzalez
 */
public class ObserverPantallaTemperatura extends javax.swing.JFrame implements Observer, Runnable {
    
    private Thread miHilo;
    private ObservableClima temperatura;
    /**
     * Creates new form ObserverPantallaTemperatura
     * @param t
     */
    public ObserverPantallaTemperatura(ObservableClima t) {
        initComponents();
        this.temperatura = t;
        this.LabelCelsius.setText("");
        this.LabelFahrenheit.setText("");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTitulo = new javax.swing.JLabel();
        LabelCelsius = new javax.swing.JLabel();
        LabelFahrenheit = new javax.swing.JLabel();
        tituloCelsius = new javax.swing.JLabel();
        tituloFahrenheit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        LabelTitulo.setText("Temperatura Actual:");
        LabelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LabelCelsius.setText("LabelCelsius");

        LabelFahrenheit.setText("LabelFahrenheit");

        tituloCelsius.setText("Celsius:");

        tituloFahrenheit.setText("Fahrenheit:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(LabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloCelsius)
                    .addComponent(tituloFahrenheit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelFahrenheit)
                    .addComponent(LabelCelsius))
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LabelTitulo)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCelsius)
                    .addComponent(tituloCelsius))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelFahrenheit)
                    .addComponent(tituloFahrenheit))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    @Override
    public void run() {
        while (true) {
            try {
                miHilo.sleep(10000);
                this.LabelCelsius.setText(
                        Float.toString( (float) temperatura.getTemperatura() ) + " ºC"
                );
                
                float fahrenheit = (float) ((temperatura.getTemperatura() * 1.8) + 32);
                this.LabelFahrenheit.setText(Float.toString(fahrenheit) + " ºF");
                
            } catch (InterruptedException ex) {
                System.err.println(ex.getMessage());
            }
        }
    }
    
    public void start(){
        miHilo = new Thread(this);
        miHilo.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCelsius;
    private javax.swing.JLabel LabelFahrenheit;
    private javax.swing.JLabel LabelTitulo;
    private javax.swing.JLabel tituloCelsius;
    private javax.swing.JLabel tituloFahrenheit;
    // End of variables declaration//GEN-END:variables
}
