/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package S3Modificado;

import java.awt.Color;
import static java.lang.Math.PI;

/**
 *
 * @author luisg
 */
public class Salpicadero extends javax.swing.JFrame {

    private float RPM;
    private EstadoMotor estadoM;
    private Controlador controlador;
    
    
    private void soltar(){
        estadoM = EstadoMotor.ENCENDIDO;
        controlador.modificarEstado(estadoM);
        RadioCentrado.setEnabled(true);
        RadioCentrado.doClick();
        RadioCentrado.setEnabled(false);
    }
    
    private void pulsarAcelerar(){
        estadoM = EstadoMotor.ACELERANDO;
        controlador.modificarEstado(EstadoMotor.ACELERANDO);
        RadioAcelerar.setEnabled(true);
        RadioAcelerar.doClick();
        RadioAcelerar.setEnabled(false);
    }

    
    private void pulsarMantener(){
        estadoM = EstadoMotor.MANTENER;
        controlador.encenderAutomatico(RPM);
        CampoVelocidad.setText(""+(2 * PI * 0.15f * RPM * (60f/1000f)));
        RadioMantener.setEnabled(true);
        RadioMantener.doClick();
        RadioMantener.setEnabled(false);
    }

    
    private void pulsarFrenar(){
        estadoM = EstadoMotor.FRENANDO;
        controlador.modificarEstado(EstadoMotor.FRENANDO);
        RadioFrenar.setEnabled(true);
        RadioFrenar.doClick();
        RadioFrenar.setEnabled(false);
    }

    
    private void pulsarReiniciar(){
        estadoM = EstadoMotor.REINICIANDO;
        controlador.reiniciarAutomatico();
        RadioReiniciar.setEnabled(true);
        RadioReiniciar.doClick();
        RadioReiniciar.setEnabled(false);
    }

    
    /**
     * @param controlador El controlador del motor
     */
    public Salpicadero() {
        initComponents();
        this.RPM = 0;
        RadioAcelerar.setEnabled(false);
        RadioFrenar.setEnabled(false);
        RadioMantener.setEnabled(false);
        RadioReiniciar.setEnabled(false);
        RadioCentrado.setEnabled(false);
        Frenar.setEnabled(false);
        Acelerar.setEnabled(false);
        Mantener.setEnabled(false);
        Reiniciar.setEnabled(false);
    }
    
    public void setReferencias(Controlador controlador){
        this.controlador = controlador;
    }
    
    public void pushRPM(float RPM, EstadoMotor estado){
        this.RPM = RPM;
        CampoVelocidadActual.setText((2 * PI * 0.15f * RPM * (60f/1000f))+" km/h");
        if(estadoM == EstadoMotor.REINICIANDO && estado == EstadoMotor.MANTENER){
            pulsarMantener();
        }
        this.estadoM = estado;
        
    }
    
    /*public void pushEstado(EstadoMotor estado){
        this.estado = estado;
    }*/
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Palanca = new javax.swing.ButtonGroup();
        PanelCruz = new javax.swing.JPanel();
        PHorizontal1 = new javax.swing.JPanel();
        PVertical1 = new javax.swing.JPanel();
        RadioFrenar = new javax.swing.JRadioButton();
        RadioAcelerar = new javax.swing.JRadioButton();
        RadioReiniciar = new javax.swing.JRadioButton();
        RadioMantener = new javax.swing.JRadioButton();
        RadioCentrado = new javax.swing.JRadioButton();
        Reiniciar = new javax.swing.JButton();
        Mantener = new javax.swing.JButton();
        Acelerar = new javax.swing.JButton();
        Frenar = new javax.swing.JButton();
        EncendidoApagado = new javax.swing.JToggleButton();
        Informacion = new javax.swing.JLabel();
        VelocidadLabel = new javax.swing.JLabel();
        CampoVelocidad = new javax.swing.JLabel();
        APAGAR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CampoVelocidadActual = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PHorizontal1.setBackground(new java.awt.Color(255, 255, 0));
        PHorizontal1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PHorizontal1.setFocusable(false);
        PHorizontal1.setOpaque(false);

        javax.swing.GroupLayout PHorizontal1Layout = new javax.swing.GroupLayout(PHorizontal1);
        PHorizontal1.setLayout(PHorizontal1Layout);
        PHorizontal1Layout.setHorizontalGroup(
            PHorizontal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        PHorizontal1Layout.setVerticalGroup(
            PHorizontal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        PVertical1.setBackground(new java.awt.Color(255, 255, 0));
        PVertical1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PVertical1.setEnabled(false);
        PVertical1.setFocusable(false);
        PVertical1.setOpaque(false);

        javax.swing.GroupLayout PVertical1Layout = new javax.swing.GroupLayout(PVertical1);
        PVertical1.setLayout(PVertical1Layout);
        PVertical1Layout.setHorizontalGroup(
            PVertical1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        PVertical1Layout.setVerticalGroup(
            PVertical1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        Palanca.add(RadioFrenar);
        RadioFrenar.setText("jRadioButton1");
        RadioFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioFrenarActionPerformed(evt);
            }
        });

        Palanca.add(RadioAcelerar);
        RadioAcelerar.setText("jRadioButton2");

        Palanca.add(RadioReiniciar);
        RadioReiniciar.setText("jRadioButton4");

        Palanca.add(RadioMantener);
        RadioMantener.setText("jRadioButton3");

        Palanca.add(RadioCentrado);
        RadioCentrado.setText("jRadioButton1");
        RadioCentrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCentradoActionPerformed(evt);
            }
        });

        Reiniciar.setText("REINICIAR");
        Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarActionPerformed(evt);
            }
        });

        Mantener.setText("MANTENER");
        Mantener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenerActionPerformed(evt);
            }
        });

        Acelerar.setText("ACELERAR");
        Acelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcelerarActionPerformed(evt);
            }
        });

        Frenar.setText("FRENAR");
        Frenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCruzLayout = new javax.swing.GroupLayout(PanelCruz);
        PanelCruz.setLayout(PanelCruzLayout);
        PanelCruzLayout.setHorizontalGroup(
            PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCruzLayout.createSequentialGroup()
                .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCruzLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(Frenar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(RadioFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                        .addComponent(RadioMantener, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(Mantener))
                    .addGroup(PanelCruzLayout.createSequentialGroup()
                        .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelCruzLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RadioAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelCruzLayout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(Reiniciar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelCruzLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(Acelerar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCruzLayout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(PHorizontal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(103, Short.MAX_VALUE)))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCruzLayout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(PVertical1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(155, Short.MAX_VALUE)))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCruzLayout.createSequentialGroup()
                    .addContainerGap(139, Short.MAX_VALUE)
                    .addComponent(RadioCentrado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        PanelCruzLayout.setVerticalGroup(
            PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCruzLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Acelerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioFrenar)
                    .addComponent(RadioMantener, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Mantener)
                    .addComponent(Frenar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(RadioReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reiniciar)
                .addGap(34, 34, 34))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCruzLayout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(PHorizontal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCruzLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(PVertical1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCruzLayout.createSequentialGroup()
                    .addContainerGap(113, Short.MAX_VALUE)
                    .addComponent(RadioCentrado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(116, Short.MAX_VALUE)))
        );

        EncendidoApagado.setText("APAGADO");
        EncendidoApagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncendidoApagadoActionPerformed(evt);
            }
        });

        VelocidadLabel.setText("VELOCIDAD ESPERADA : ");

        APAGAR.setText("APAGAR MOTOR");
        APAGAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APAGARActionPerformed(evt);
            }
        });

        jLabel1.setText("VELOCIDAD ACTUAL :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(Informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(VelocidadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CampoVelocidad, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(CampoVelocidadActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EncendidoApagado)
                        .addGap(217, 217, 217)
                        .addComponent(PanelCruz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(APAGAR)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(APAGAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoVelocidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VelocidadLabel))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(EncendidoApagado)
                                .addGap(184, 184, 184))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(PanelCruz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CampoVelocidadActual, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioFrenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioFrenarActionPerformed

    private void RadioCentradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCentradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioCentradoActionPerformed
 
    private void EncendidoApagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncendidoApagadoActionPerformed
        if(EncendidoApagado.isSelected()){
            Acelerar.setEnabled(true);
            Frenar.setEnabled(true);
            Reiniciar.setEnabled(false);
            Mantener.setEnabled(false);
            EncendidoApagado.setText("APAGAR");
            EncendidoApagado.setForeground(Color.red);
            Informacion.setText("ENCENDIDO");
            controlador.modificarEstado(EstadoMotor.ENCENDIDO);
        } else{
            Acelerar.setEnabled(false);
            Frenar.setEnabled(false);
            Mantener.setEnabled(false);
            Reiniciar.setEnabled(false);
            EncendidoApagado.setText("ENCENDER");
            EncendidoApagado.setForeground(Color.green);
            Informacion.setText("APAGADO");
            controlador.modificarEstado(EstadoMotor.APAGADO);
        }
    }//GEN-LAST:event_EncendidoApagadoActionPerformed

    private void FrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenarActionPerformed
        if(estadoM != EstadoMotor.FRENANDO){
            pulsarFrenar();
        }else{
            soltar();
        }
    }//GEN-LAST:event_FrenarActionPerformed

    private void ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarActionPerformed
        if(estadoM != EstadoMotor.REINICIANDO){
            pulsarReiniciar();
        }else{
            soltar();
        }
    }//GEN-LAST:event_ReiniciarActionPerformed

    private void MantenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenerActionPerformed
        if(estadoM != EstadoMotor.MANTENER){ 
            pulsarMantener();
        }else{
            soltar();
        }
    }//GEN-LAST:event_MantenerActionPerformed

    private void AcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcelerarActionPerformed
        if(estadoM != EstadoMotor.ACELERANDO){   
            pulsarAcelerar();
            Mantener.setEnabled(true);
            Reiniciar.setEnabled(true);
        }else{
            soltar();
        }
    }//GEN-LAST:event_AcelerarActionPerformed

    private void APAGARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APAGARActionPerformed
        controlador.apagarMotor();
    }//GEN-LAST:event_APAGARActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salpicadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salpicadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salpicadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salpicadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salpicadero().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton APAGAR;
    private javax.swing.JButton Acelerar;
    private javax.swing.JLabel CampoVelocidad;
    private javax.swing.JLabel CampoVelocidadActual;
    private javax.swing.JToggleButton EncendidoApagado;
    private javax.swing.JButton Frenar;
    private javax.swing.JLabel Informacion;
    private javax.swing.JButton Mantener;
    private javax.swing.JPanel PHorizontal1;
    private javax.swing.JPanel PVertical1;
    private javax.swing.ButtonGroup Palanca;
    private javax.swing.JPanel PanelCruz;
    private javax.swing.JRadioButton RadioAcelerar;
    private javax.swing.JRadioButton RadioCentrado;
    private javax.swing.JRadioButton RadioFrenar;
    private javax.swing.JRadioButton RadioMantener;
    private javax.swing.JRadioButton RadioReiniciar;
    private javax.swing.JButton Reiniciar;
    private javax.swing.JLabel VelocidadLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
