/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modeloObservable;

import java.util.Observer;
import java.util.Observable;

/**
 *
 * @author Jose Jiménez
 * @author Alberto Llamas
 */
public class CambiadorTemperatura extends javax.swing.JFrame implements Observer{
    private ObservableClima temperatura;
    /**
     * Creates new form CambiadorTemperatura
     */
    public CambiadorTemperatura(ObservableClima t) {
        initComponents();
        this.labelTempActual.setText("");
        this.temperatura = t;
        this.setLocation(0, 400);
        this.setVisible(true);
    }
    
    @Override
    public void update(Observable o, Object arg){
        float t = (float) arg;
        this.labelTempActual.setText(Float.toString(t));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloTempActual = new javax.swing.JLabel();
        labelTituloNuevaTemp = new javax.swing.JLabel();
        fieldNuevaTemp = new javax.swing.JTextField();
        labelTempActual = new javax.swing.JLabel();
        botonCambio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloTempActual.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        tituloTempActual.setText("Temperatura Actual (en grados): ");

        labelTituloNuevaTemp.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        labelTituloNuevaTemp.setText("Nueva Temperatura: ");

        fieldNuevaTemp.setText("Nueva Temperatura");
        fieldNuevaTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNuevaTempActionPerformed(evt);
            }
        });

        labelTempActual.setText("jLabel2");

        botonCambio.setText("Cambiar Temperatura");
        botonCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTituloNuevaTemp)
                    .addComponent(tituloTempActual))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTempActual)
                    .addComponent(fieldNuevaTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCambio)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloTempActual)
                    .addComponent(labelTempActual))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTituloNuevaTemp)
                    .addComponent(fieldNuevaTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(botonCambio)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNuevaTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNuevaTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNuevaTempActionPerformed

    private void botonCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambioActionPerformed
        // TODO add your handling code here:
        if (!this.fieldNuevaTemp.getText().isBlank()){
                        float t = Float.valueOf(this.fieldNuevaTemp.getText());
            temperatura.setTemperatura(t);
        }
        this.fieldNuevaTemp.setText("");
    }//GEN-LAST:event_botonCambioActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCambio;
    private javax.swing.JTextField fieldNuevaTemp;
    private javax.swing.JLabel labelTempActual;
    private javax.swing.JLabel labelTituloNuevaTemp;
    private javax.swing.JLabel tituloTempActual;
    // End of variables declaration//GEN-END:variables
}
