/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package S3Modificado;

import java.awt.Color;

/**
 *
 * @author luisg
 */
public class Salpicadero extends javax.swing.JFrame {

    private float RPM;
    private EstadoMotor estadoM;
    private Controlador controlador;
    
    
    private void pulsarAcelerar(){
        controlador.modificarEstado(EstadoMotor.ACELERANDO);
        RadioAcelerar.setEnabled(true);
        RadioAcelerar.doClick();
        RadioAcelerar.setEnabled(false);
    }
    
    private void soltarAcelerar(){
        controlador.modificarEstado(EstadoMotor.ENCENDIDO);
        RadioCentrado.setEnabled(true);
        RadioCentrado.doClick();
        RadioCentrado.setEnabled(false);
    }
    
    private void pulsarMantener(){
        controlador.encenderAutomatico(RPM);
        RadioMantener.setEnabled(true);
        RadioMantener.doClick();
        RadioMantener.setEnabled(false);
    }
    
    private void soltarMantener(){
        controlador.modificarEstado(EstadoMotor.ENCENDIDO);
        RadioCentrado.setEnabled(true);
        RadioCentrado.doClick();
        RadioCentrado.setEnabled(false);
    }
    
    private void pulsarFrenar(){
        controlador.modificarEstado(EstadoMotor.FRENANDO);
        RadioFrenar.setEnabled(true);
        RadioFrenar.doClick();
        RadioFrenar.setEnabled(false);
    }
    
    private void soltarFrenar(){
        controlador.modificarEstado(EstadoMotor.ENCENDIDO);
        RadioCentrado.setEnabled(true);
        RadioCentrado.doClick();
        RadioCentrado.setEnabled(false);
    }
    
    private void pulsarReiniciar(){
        controlador.reiniciarAutomatico();
        RadioReiniciar.setEnabled(true);
        RadioReiniciar.doClick();
        RadioReiniciar.setEnabled(false);
    }
    
    private void soltarReiniciar(){
        controlador.modificarEstado(EstadoMotor.ENCENDIDO);
        RadioCentrado.setEnabled(true);
        RadioCentrado.doClick();
        RadioCentrado.setEnabled(false);
    }
    
    /**
     * @param controlador El controlador del motor
     */
    public Salpicadero() {
        initComponents();
        this.RPM = 0;
        RadioAcelerar.setEnabled(false);
        RadioFrenar.setEnabled(false);
        RadioReiniciar.setEnabled(false);
        RadioMantener.setEnabled(false);
        RadioCentrado.setEnabled(false);
        Frenar.setEnabled(false);
        Acelerar.setEnabled(false);
        Mantener.setEnabled(false);
        Reiniciar.setEnabled(false);
    }
    
    public void setReferencias(Controlador controlador){
        this.controlador = controlador;
    }
    
    public void pushRPM(float RPM, EstadoMotor estado){
        this.RPM = RPM;
        if(estadoM == EstadoMotor.REINICIANDO && estado == EstadoMotor.MANTENER){
            soltarMantener();
            Mantener.doClick();
        }
        this.estadoM = estado;
        
    }
    
    /*public void pushEstado(EstadoMotor estado){
        this.estado = estado;
    }*/
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Palanca = new javax.swing.ButtonGroup();
        PanelCruz = new javax.swing.JPanel();
        PHorizontal1 = new javax.swing.JPanel();
        PVertical1 = new javax.swing.JPanel();
        RadioFrenar = new javax.swing.JRadioButton();
        RadioAcelerar = new javax.swing.JRadioButton();
        RadioMantener = new javax.swing.JRadioButton();
        RadioReiniciar = new javax.swing.JRadioButton();
        RadioCentrado = new javax.swing.JRadioButton();
        Acelerar = new javax.swing.JToggleButton();
        Frenar = new javax.swing.JToggleButton();
        Mantener = new javax.swing.JToggleButton();
        Reiniciar = new javax.swing.JToggleButton();
        EncendidoApagado = new javax.swing.JToggleButton();
        Informacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PHorizontal1.setBackground(new java.awt.Color(255, 255, 0));
        PHorizontal1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PHorizontal1.setFocusable(false);
        PHorizontal1.setOpaque(false);

        javax.swing.GroupLayout PHorizontal1Layout = new javax.swing.GroupLayout(PHorizontal1);
        PHorizontal1.setLayout(PHorizontal1Layout);
        PHorizontal1Layout.setHorizontalGroup(
            PHorizontal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 132, Short.MAX_VALUE)
        );
        PHorizontal1Layout.setVerticalGroup(
            PHorizontal1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );

        PVertical1.setBackground(new java.awt.Color(255, 255, 0));
        PVertical1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PVertical1.setEnabled(false);
        PVertical1.setFocusable(false);
        PVertical1.setOpaque(false);

        javax.swing.GroupLayout PVertical1Layout = new javax.swing.GroupLayout(PVertical1);
        PVertical1.setLayout(PVertical1Layout);
        PVertical1Layout.setHorizontalGroup(
            PVertical1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        PVertical1Layout.setVerticalGroup(
            PVertical1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 113, Short.MAX_VALUE)
        );

        Palanca.add(RadioFrenar);
        RadioFrenar.setText("jRadioButton1");
        RadioFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioFrenarActionPerformed(evt);
            }
        });

        RadioAcelerar.setBackground(new java.awt.Color(51, 51, 51));
        Palanca.add(RadioAcelerar);
        RadioAcelerar.setText("jRadioButton2");

        Palanca.add(RadioMantener);
        RadioMantener.setText("jRadioButton4");

        Palanca.add(RadioReiniciar);
        RadioReiniciar.setText("jRadioButton3");

        Palanca.add(RadioCentrado);
        RadioCentrado.setText("jRadioButton1");
        RadioCentrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioCentradoActionPerformed(evt);
            }
        });

        Acelerar.setText("ACELERAR");
        Acelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcelerarActionPerformed(evt);
            }
        });

        Frenar.setText("FRENAR");
        Frenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrenarActionPerformed(evt);
            }
        });

        Mantener.setText("MANTENER");
        Mantener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenerActionPerformed(evt);
            }
        });

        Reiniciar.setText("REINICIAR");
        Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCruzLayout = new javax.swing.GroupLayout(PanelCruz);
        PanelCruz.setLayout(PanelCruzLayout);
        PanelCruzLayout.setHorizontalGroup(
            PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCruzLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(Frenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(RadioReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Mantener)
                .addContainerGap())
            .addGroup(PanelCruzLayout.createSequentialGroup()
                .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCruzLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioMantener, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RadioAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelCruzLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(Acelerar))
                    .addGroup(PanelCruzLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(Reiniciar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCruzLayout.createSequentialGroup()
                    .addGap(80, 80, 80)
                    .addComponent(PHorizontal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCruzLayout.createSequentialGroup()
                    .addGap(132, 132, 132)
                    .addComponent(PVertical1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(145, Short.MAX_VALUE)))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCruzLayout.createSequentialGroup()
                    .addContainerGap(139, Short.MAX_VALUE)
                    .addComponent(RadioCentrado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(160, Short.MAX_VALUE)))
        );
        PanelCruzLayout.setVerticalGroup(
            PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCruzLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Acelerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioAcelerar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioFrenar)
                    .addComponent(RadioReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Frenar)
                    .addComponent(Mantener))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(RadioMantener, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reiniciar)
                .addGap(34, 34, 34))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCruzLayout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(PHorizontal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelCruzLayout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(PVertical1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(64, Short.MAX_VALUE)))
            .addGroup(PanelCruzLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCruzLayout.createSequentialGroup()
                    .addContainerGap(113, Short.MAX_VALUE)
                    .addComponent(RadioCentrado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(116, Short.MAX_VALUE)))
        );

        EncendidoApagado.setText("APAGADO");
        EncendidoApagado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncendidoApagadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(EncendidoApagado)
                        .addGap(356, 356, 356))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(Informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)))
                .addComponent(PanelCruz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PanelCruz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(EncendidoApagado)
                        .addGap(182, 182, 182))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioFrenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioFrenarActionPerformed

    private void RadioCentradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioCentradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioCentradoActionPerformed

    private void AcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcelerarActionPerformed
        if(Acelerar.isSelected()){
            pulsarAcelerar();
            Mantener.setEnabled(true);
        }else{
            soltarAcelerar();
        }
    }//GEN-LAST:event_AcelerarActionPerformed

    private void MantenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenerActionPerformed
       pulsarMantener();
    }//GEN-LAST:event_MantenerActionPerformed

    private void ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarActionPerformed
        pulsarReiniciar();
    }//GEN-LAST:event_ReiniciarActionPerformed

    private void FrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrenarActionPerformed
        if(Frenar.isSelected()){
            if(Mantener.isSelected())soltarMantener();
            if(Reiniciar.isSelected())Reiniciar.doClick();
            pulsarFrenar();
        }else{
            soltarFrenar();
        }
    }//GEN-LAST:event_FrenarActionPerformed

    private void EncendidoApagadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncendidoApagadoActionPerformed
        if(EncendidoApagado.isSelected()){
            Acelerar.setEnabled(true);
            Frenar.setEnabled(true);
            Reiniciar.setEnabled(false);
            Mantener.setEnabled(false);
            EncendidoApagado.setText("APAGAR");
            EncendidoApagado.setForeground(Color.red);
            Informacion.setText("ENCENDIDO");
            controlador.modificarEstado(EstadoMotor.ENCENDIDO);
        } else{
            if(Acelerar.isSelected()) soltarAcelerar();
            Acelerar.setEnabled(false);
            if(Frenar.isSelected())soltarFrenar();
            Frenar.setEnabled(false);
            if(Mantener.isSelected())soltarMantener();
            Mantener.setEnabled(false);
            if(Reiniciar.isSelected())Reiniciar.doClick();
            Reiniciar.setEnabled(false);
            EncendidoApagado.setText("ENCENDER");
            EncendidoApagado.setForeground(Color.green);
            Informacion.setText("APAGADO");
            controlador.modificarEstado(EstadoMotor.APAGADO);
        }
    }//GEN-LAST:event_EncendidoApagadoActionPerformed

    /**
     * @param args the command line arguments
     */
   // public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salpicadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salpicadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salpicadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salpicadero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salpicadero().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Acelerar;
    private javax.swing.JToggleButton EncendidoApagado;
    private javax.swing.JToggleButton Frenar;
    private javax.swing.JLabel Informacion;
    private javax.swing.JToggleButton Mantener;
    private javax.swing.JPanel PHorizontal1;
    private javax.swing.JPanel PVertical1;
    private javax.swing.ButtonGroup Palanca;
    private javax.swing.JPanel PanelCruz;
    private javax.swing.JRadioButton RadioAcelerar;
    private javax.swing.JRadioButton RadioCentrado;
    private javax.swing.JRadioButton RadioFrenar;
    private javax.swing.JRadioButton RadioMantener;
    private javax.swing.JRadioButton RadioReiniciar;
    private javax.swing.JToggleButton Reiniciar;
    // End of variables declaration//GEN-END:variables
}
